Notes for the course Python for Data Science and Machine Learning Bootcamp https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones((2,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [16]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand(5)

array([ 0.32693785,  0.36849375,  0.62198262,  0.92815347,  0.80708274])

In [19]:
np.random.rand(5,5)

array([[ 0.84472003,  0.98790773,  0.67087169,  0.65762396,  0.57193807],
       [ 0.61544423,  0.0062417 ,  0.12368507,  0.79736435,  0.427032  ],
       [ 0.92175352,  0.18939719,  0.75815736,  0.92224027,  0.03642557],
       [ 0.86195388,  0.82055926,  0.33176483,  0.85682564,  0.00317235],
       [ 0.43665573,  0.34605801,  0.72047759,  0.04322717,  0.98675672]])

In [20]:
np.random.randn(2)

array([-0.8824065 , -0.23107457])

In [21]:
np.random.randn(4,4)

array([[-0.69489344,  1.18599768, -0.74768171,  1.13490507],
       [ 1.51480602,  0.7181154 , -0.23906068,  0.22913503],
       [ 0.24296911, -1.52287634,  1.07068885, -1.20690461],
       [ 0.29039008,  0.74479647,  0.05349434,  0.0921641 ]])

In [22]:
np.random.randint(1,100)

95

In [23]:
np.random.randint(1,100,10)

array([30,  5, 99, 58, 21, 64, 27, 85, 40, 84])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0,50,10)

In [28]:
ranarr

array([49, 39, 29,  5,  5, 24,  7,  8,  5, 17])

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([49, 39, 29,  5,  5, 24,  7,  8,  5, 17])

In [32]:
ranarr.max()

49

In [33]:
ranarr.min()

5

In [34]:
ranarr.argmax()

0

In [36]:
ranarr.argmin()

3

In [38]:
arr.shape

(25,)

In [43]:
arr=arr.reshape(5,5)

In [44]:
arr.shape

(5, 5)

In [45]:
arr.dtype

dtype('int64')

In [46]:
from numpy.random import randint

In [47]:
randint(2,10)

9

In [49]:
arr = np.arange(0,10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[8]

8

In [52]:
arr[1:5]

array([1, 2, 3, 4])

In [53]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [54]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [55]:
arr[6]

6

In [56]:
arr[5:]

array([5, 6, 7, 8, 9])

(everything beyond index 5)

In [57]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [58]:
arr[0:5]=100

In [59]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [60]:
arr =np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_arr=arr[0:6]

In [63]:
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [64]:
slice_of_arr[:]=99

In [65]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [66]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

slice is a reference to a part of the original array;
if you want a copy, you need to explicitely specify it

In [67]:
arr_copy=arr.copy()

In [68]:
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [69]:
arr_copy[:]=100

In [70]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [71]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [72]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [73]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [75]:
arr_2d[0][0]

5

In [76]:
arr_2d[0]

array([ 5, 10, 15])

In [77]:
arr_2d[1][1]

25

In [78]:
arr_2d[2][1]

40

In [79]:
arr_2d[2,1]

40

In [80]:
arr_2d[1,2]

30

In [81]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [82]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [83]:
arr_2d[1,:]

array([20, 25, 30])

In [84]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [85]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

Now move on th conditional selection

Now move on to conditional selection

In [87]:
arr =np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [90]:
bool_arr = arr > 5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [92]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr<3]

array([1, 2])

In [94]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
arr_2d=np.arange(50).reshape(5,10)

In [96]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [99]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [100]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [101]:
arr = np.arange(0,11)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [104]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr+100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [108]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [109]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [110]:
1/0

ZeroDivisionError: division by zero

In [111]:
arr/arr

/home/ekaterina/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

Very first element is zero; python would say "ERROR", numpy says "Warning"

In [113]:
1/arr

/home/ekaterina/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [114]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Now, Universal array functions

In [115]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [119]:
np.max(arr)

10

In [120]:
arr.max()

10

In [123]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

full list available on the web

https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.math.html